mall/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
app_name='mall'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:stuff_id>/',views.detail,name='detail'),
    path('register/',views.register,name='register'),
    path('info/',views.info,name='info'),
    path('cart/',views.cart,name='cart'),
    path('cart/<int:stuff_id>/add',views.addCart,name='addcart'),
    path('cart/<int:stuff_id>/delete',views.subCart,name='subCart'),
    path('cart/<int:stuff_id>/plus',views.plusStuff,name='plusStuff'),
    path('cart/<int:stuff_id>/minus',views.minusStuff,name='minusStuff'),
    path('buy/<int:stuff_id>/',views.buyAtIndex, name='buyAtIndex'),
    path('buy/',views.buy, name='buy'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from mall import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/',include('mall.urls')),
    path('common/',include('common.urls')),
    path('',views.index,name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mall/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class Stuff(models.Model):
    id=models.BigAutoField(primary_key=True)
    name=models.CharField(max_length=20)
    price=models.IntegerField()
    detail=models.TextField(max_length=300)
    quantity=models.IntegerField(default=0)
    image=models.ImageField(upload_to="",blank=True,verbose_name='stuff_img')
    pub_date=models.DateTimeField()

    def __str__(self):
        return self.name

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    stuffs=models.ForeignKey(Stuff,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    def __str__(self):
        return self.user.username +' '+ self.stuffs.name
    
class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    stuff=models.ForeignKey(Stuff,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    order_date=models.DateTimeField()
    subtotal=models.IntegerField(default=0)

    def __str__(self):
        return self.user.username + ' ' + self.stuff.name+' '+str(self.order_date)

mall/forms.py
from django import forms
from .models import Stuff

class StuffForm(forms.ModelForm):
    class Meta:
        model = Stuff
        fields = ['name','price','detail','image']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'detail': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
            'image':forms.FileInput(attrs = {"id" : "image_field",'class':'form-control'}),
        }

mall/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Stuff,Cart,Order
from .forms import StuffForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import datetime,timedelta
# Create your views here.

def index(request):
    stuffs=Stuff.objects.all()
    context={'stuffs':stuffs}
    return render(request,'mall/index.html',context)

def detail(request,stuff_id):
    stuff=Stuff.objects.get(id=stuff_id)
    context={'stuff':stuff}
    return render(request,'mall/detail.html',context)

def register(request):
    if request.method=="POST":
        stuff=Stuff(name=request.POST.get('name'),price=request.POST.get('price'),detail=request.POST.get('detail'),image=request.FILES.get('image'))
        stuff.pub_date=timezone.now()+timedelta(hours=9)
        stuff.save()
        return redirect('mall:index')
    else:
        form=StuffForm()
        return render(request,'mall/register.html',{'form':form})

@login_required(login_url='common:login')
def info(request):
    orders=Order.objects.filter(user=request.user)
    pub_times=[]
    orderlists=[]
    for order in orders:
        pub_times.append(order.order_date)
    pub_times=list(set(pub_times))
    for pub_time in pub_times:
        total=0
        orders=Order.objects.filter(order_date=pub_time)
        for order in orders:
            total+=order.subtotal
        orderlists.append([orders,total])
    context={'orderlists':orderlists,'username':request.user.username,'email':request.user.email}
    return render(request,'mall/info.html',context)

@login_required(login_url='common:login')
def cart(request):
    uCart=Cart.objects.filter(user=request.user)
    stuffs=uCart
    context={'stuffs':stuffs}
    return render(request,'mall/cart.html',context)

@login_required(login_url='common:login')
def addCart(request,stuff_id):
    uCart=Cart.objects.filter(user=request.user)
    stuff=Stuff.objects.get(id=stuff_id)
    for uCart2 in uCart:
        if uCart2.stuffs.id==stuff_id:
            uCart2.quantity+=1
            uCart2.save()
            break
    else:
        uCart2=Cart.objects.create(user=request.user,stuffs=stuff)
        uCart2.quantity+=1
        uCart2.save()
        
    return  redirect('mall:cart')

@login_required(login_url='common:login')
def subCart(request,stuff_id):
    uCart=Cart.objects.filter(user=request.user)
    for uCart2 in uCart:
        if uCart2.stuffs.id==stuff_id:
            uCart2.delete()
            break
    return  redirect('mall:cart')

@login_required(login_url='common:login')
def plusStuff(request,stuff_id):
    uCart=Cart.objects.filter(user=request.user)
    for uCart2 in uCart:
        if uCart2.stuffs.id==stuff_id:
            uCart2.quantity+=1
            uCart2.save()
            break
    return  redirect('mall:cart')

@login_required(login_url='common:login')
def minusStuff(request,stuff_id):
    uCart=Cart.objects.filter(user=request.user)
    for uCart2 in uCart:
        if uCart2.stuffs.id==stuff_id:
            uCart2.quantity-=1
            uCart2.save()
            if uCart2.quantity==0:
                uCart2.delete()
            break
    return  redirect('mall:cart')


@login_required(login_url='common:login')
def buyAtIndex(request,stuff_id):
    uCart=Cart.objects.filter(user=request.user)
    stuff=Stuff.objects.get(id=stuff_id)
    for uCart2 in uCart:
        if uCart2.stuffs.id==stuff_id:
            uCart2.quantity+=1
            uCart2.save()
            break
    else:
        uCart2=Cart.objects.create(user=request.user,stuffs=stuff)
        uCart2.quantity+=1
        uCart2.save()
    return  redirect('mall:cart')

@login_required(login_url='common:login')
def buy(request):
    subtotal=0
    order_date=datetime.now()
    if request.method == 'POST':
        uCarts=Cart.objects.filter(user=request.user)
        for uCart in uCarts:
            if request.POST.get(uCart.stuffs.name):
                stuff_name = request.POST[uCart.stuffs.name]
                stuff=Stuff.objects.get(name=stuff_name)
                uCart=Cart.objects.get(user=request.user,stuffs=stuff)
                orderlist=Order.objects.create(user=request.user,stuff=uCart.stuffs,order_date=order_date,quantity=uCart.quantity)
                orderlist.save()
                subtotal=uCart.quantity*uCart.stuffs.price
                orderlist.subtotal=subtotal
                orderlist.save()

        orders=Order.objects.filter(user=request.user)
        pub_times=[]
        orderlists=[]
        for order in orders:
            pub_times.append(order.order_date)
        pub_times=list(set(pub_times))
        for pub_time in pub_times:
            orders=Order.objects.filter(order_date=pub_time)
            total=0
            for order in orders:
                total+=order.subtotal
            orderlists.append([orders,total])
        context={'orderlists':orderlists,'username':request.user.username,'email':request.user.email}
    else:
        context={'username':request.user.username,'email':request.user.email}
    return  render(request,'mall/info.html',context)

templates/mall/cart.html
{% extends 'base.html' %}
{% load static %}
{% block link%}
<link rel="stylesheet" type="text/css" href="{% static 'cart/cartStyle.css' %}">
{% endblock %}
{% block content %}
<script>
    function getCheckboxValue()  {
        // 선택된 목록 가져오기
        const list_=document.getElementsByClassName('form-check-input');
        document.getElementById('sum').innerText
          = list_;  
        const buyStuff=document.getElementById('buyStuff');
        // 선택된 목록에서 value 찾기
        let result = parseInt(0);
        let len = list_.length;
        let check=false;
        buyStuff.innerHTML='';
        for (let i=0;i<len;i++){
            element=list_.item(i)
            if (element.checked)
            {
            let hidden_val=document.createElement('input');
            hidden_val.setAttribute("type", "hidden");
            hidden_val.value=element.name;
            hidden_val.name=element.name;
            hidden_val.checked=true;
            buyStuff.appendChild(hidden_val);
            result+=parseInt(element.value)
            check=true
            }
            }
        
        // 출력
        document.getElementById('sum').innerText
          = result;
      }
      window.onload=function(){
        getCheckboxValue()
      }
    </script>
    {% if stuffs %}
<div class="card">
  <div class="card-header">
    CART
  </div>
  <div class="card-body">
    <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col">Goods</th>
            <th scope="col">Price</th>
            <th scope="col">Count</th>
            <th scope="col"> </th>
            <th scope="col">PriceSum</th>
            <th scope="col"> </th>
          </tr>
        </thead>
        <tbody>
            {% for stuff in stuffs %}
          <tr>
            <th scope="row"><div class="form-check">
                    <input class="form-check-input" type="checkbox" name="{{stuff.stuffs.name}}" value="{% widthratio stuff.stuffs.price 1 stuff.quantity %}" id="flexCheckDefault" onclick=getCheckboxValue() checked>
                </div></th>
            <th>{{forloop.counter}}</th>
            <td >{{ stuff.stuffs.name }}</td>
            <td>{{stuff.stuffs.price}}$</td>
            <td>{{ stuff.quantity}} </td>
        <td><form method="post" action="{% url 'mall:plusStuff' stuff.stuffs.id %}">
            {% csrf_token %}
            <button  class="btn btn-outline-primary"
        style="--bs-btn-font-size: .1rem; border: none;" >
        ➕
</button>
        </form>
        <form method="post" action="{% url 'mall:minusStuff' stuff.stuffs.id %}" >
            {% csrf_token %}
            <button  class="btn btn-outline-primary"
        style=" --bs-btn-font-size: .1rem; border: none;">
        ➖
</button>
        </form></td>
            <td>{% widthratio stuff.stuffs.price 1 stuff.quantity %}$</td>
            <td><form method="post" action="{% url 'mall:subCart' stuff.stuffs.id %}" >
                {% csrf_token %}
                <button class="card-link badge bg-secondary"> X </button>
            </form></td>
          </tr>
          {% endfor %}
          <th scope="row"></th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td><span id="sum"></span>$</td>
          <td>                  
            <form method="post" action="{% url 'mall:buy' %}">
            {% csrf_token %}
            <div id="buyStuff">

            </div>
              <button class="btn btn-primary">BUY</button>
          </form></td>
          
        </tbody>
      </table>
  </div>
</div>
        {% else %}
        <div class="card">
  <div class="card-header">
    CART
  </div>
  <div class="card-body">

  </div>
</div>

    {% endif %}
{% endblock %}

templates/mall/detail.html
{% extends 'base.html' %}
{% load static %}
{% block link%}
<link rel="stylesheet" type="text/css" href="{% static 'mall/detailStyle.css' %}">
{% endblock %}
{% block content %}
{% if stuff %}
    <div class="card mb-3">
      <img src="/media/{{stuff.image}}" class="card-img-top h-25 w-25" alt="...">
  <!-- <img src="https://cdn.dominos.co.kr/admin/upload/goods/20200311_x8StB1t3.jpg" class="card-img-top h-25 w-25" alt="..."> -->
  <div class="card-body">
    <h5 class="card-title form-label">{{stuff.name}}</h5>
    <p class="card-text form-control">{{ stuff.detail }}</p>
          <p class="card-text form-label">{{ stuff.price }} $</p>
    <p class="card-text"><small class="text-muted">Last updated at {{stuff.pub_date}}</small></p>
  </div>
</div>
    {% endif %}
{% endblock %}

templates/mall/index.html
{% extends 'base.html' %}
{% load static%}
{% block link%}
<link rel="stylesheet" type="text/css" href="{% static 'mall/indexStyle.css' %}">
{% endblock %}
{% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
{% for stuff in stuffs %}
    <div class="card stuff mx-4" style="width: 18rem;">
      <div class="col">
    <div class="card">
  <img src="/media/{{stuff.image}}" class="card-img-top" alt="...">
        <div class="card-body">
    <h5 class="card-title">{{ stuff.name }}</h5>
    <p class="card-text">{{ stuff.price }} $</p>
  </div>
  <div class="card-body">
      <a href="{% url 'mall:buyAtIndex' stuff.id %}" class="card-link badge bg-primary" style="text-decoration-line: none;">BUY</a>
      <a href="{% url 'mall:addcart' stuff.id %}" class="card-link badge bg-primary" style="text-decoration-line: none;">ADD CART</a>
      <a href="{% url 'mall:detail' stuff.id %}" class="card-link badge bg-primary" style="text-decoration-line: none;">Detail</a>
  </div>
    </div>
  </div>
    </div>
{% endfor %}
    </div>
{% endblock %}

templates/mall/info.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
  <div class="card-header">
    About Info
  </div>
  <div class="card-body">
    <h5 class="card-title">username: {{username}}</h5>
      <h5 class="card-title">email: {{email}}</h5>
  </div>
</div>
<p></p>
{% if orderlists %}
{% for orders in orderlists%}
<div class="card">
  <div class="card-header">
    Order List
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Goods</th>
          <th scope="col">Price</th>
          <th scope="col">Count</th>
          <th scope="col">PriceSum</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders.0 %}
        <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>{{ order.stuff.name }}</td>
        <td>{{order.stuff.price}}$</td>
        <td>{{order.quantity}} </td>
        <td>{% widthratio order.stuff.price 1 order.quantity %}$</td>
      </tr>{% endfor %}
        </tbody>
    </table>
    <small class="text-muted">Ordered At {{orders.0.0.order_date}}</small><br>
    <small class="text-muted">SEND {{orders.1}}$</small> <br> 
    <small class="text-muted">xxxx-xx-xxxxxxx Kakao Bank</small>
</div>
</div>
{% endfor %}
{% endif %}
{% endblock %}

templates/mall/register.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">Register Stuff</h5>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary">Save</button>
    </form>
</div>
{% endblock %}

templates/mall/temp.html
{% extends 'base.html' %}
{% block content%}
{{buyStuff}}
{% endblock %}