common/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
app_name='common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
]

mall/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
app_name='mall'
urlpatterns = [
    path('',views.index,name='index'),
    path('<int:stuff_id>/',views.detail,name='detail'),
    path('register/',views.register,name='register'),
    path('info/',views.info,name='info'),
    path('cart/',views.cart,name='cart'),
    path('cart/<int:stuff_id>/add',views.addCart,name='addcart'),
    path('cart/<int:stuff_id>/delete',views.subCart,name='subCart'),
    path('cart/<int:stuff_id>/plus',views.plusStuff,name='plusStuff'),
    path('cart/<int:stuff_id>/minus',views.minusStuff,name='minusStuff'),
    path('buy/<int:stuff_id>/',views.buyAtIndex, name='buyAtIndex'),
    path('buy/',views.buy, name='buy'),
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from mall import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/',include('mall.urls')),
    path('common/',include('common.urls')),
    path('',views.index,name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DONGKAM SHOP</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
{% block link %}
{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'mall:index' %}">DONGKAM SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'mall:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active"  href="{% url 'mall:cart' %}">CART</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'mall:info' %}">MY</a>
        </li>
          <li class="nav-item active">
              {% if user.is_authenticated %}
    <a class="nav-link active" href="{% url 'common:logout' %}">{{ user.username }} (LOGOUT)</a>
    {% else %}
          <a class="nav-link active" href="{% url 'common:login' %}">LOGIN</a>
              {% endif %}
        </li>
                      <li>
                      {% if user.is_authenticated %}
    <a class="nav-link active" href="{% url 'mall:register' %}"> Register Goods</a>
                    {% else %}
                    <a class="nav-link active" href="{% url 'common:signup' %}">SIGNUP</a>
                    {% endif %}
                </li>

      </ul>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}